name: enable PR auto-merge

on:
  pull_request:
    types:
      - opened

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    # https://github.com/orgs/community/discussions/24686
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - run: |
          gh api graphql -f pullRequestId="${{ github.event.pull_request.node_id }}" -f query='
          mutation EnablePullRequestAutoMerge($pullRequestId: ID!) {
            enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId}) {
              clientMutationId
            }
          }
          '
        env:
          GH_TOKEN: ${{ github.token }}
